# Generated by Django 6.0.5 on 2026-05-27 23:49

from django.db import migrations

import niceid.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    niceid.fields.NiceIDPrimaryKeyField(
                        db_default=niceid.fields.UUID7(),
                        editable=False,
                        namespace="item",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
